ABT-1762: added custom mail client
softwaregroup-bg/ut-port-mail pull request #2
Opened 2017-06-27 15:37 UTC by simeonpp

2017-06-29 10:59 UTC, kalinkrustev commented
This pattern of coding is not for ports, but for business modules. Ports define how a single port operates and do not export {ports, modules, validations} structure.

2017-06-29 16:04 UTC, simeonpp commented
Updated port logic.

2017-06-30 10:18 UTC, kalinkrustev requested changes
Let's also upgrade the versions of nodemailer modules.

2017-06-30 10:18 UTC, kalinkrustev commented on index.js
> -    this.latency = this.counter && this.counter('average', 'lt', 'Latency');
Are you sure that this should be removed?

2017-06-30 10:42 UTC, merged